### ISSUE TITLE
Wiki に課題仕様を書く

### ISSUE THREAD

**Issue by naoyuki-sakai** [wbap/hackathon-2017-sample#63]
9月の海馬ハッカソンでは Unity 環境をマニュアルモードで動かす前提にしていた。

参加していない人から見てわかりにくいので、Wiki に課題の説明を追加する。

URL は以下のとおり。共有設定は WBAI のメンバー＋開催関係者のみ。
https://drive.google.com/a/wba-initiative.org/file/d/0B4I47ammhSyTaTdMaUhFUVgwMXc/view?usp=sharing

**Comment by rondelion** [comment]
現在並行して#64作業中です。
それぞれの課題について、目的（何の認知機能をテストするためのものか）を簡単に追加していただけないでしょうか＞@haruom

**Comment by rondelion** [comment]
後半の「仕様の背景」は最初に置いてください。また、わかりづらいところ（「皆が苦労していた」など）があるので、推敲をお願いします。
参考：英訳案 https://goo.gl/9bPu3j
また、図では鉄塔、山、となっていますが、本文ではスカイツリー、富士山になっているので、統一が必要です。

**Comment by naoyuki-sakai** [comment]
一旦、文言のみを作成しました。

https://github.com/wbap/hackathon-2017-sample/wiki/MazeAndTaskSpecification

残作業は、画像を GitHub の image ブランチにプッシュし、リンクを貼ることです。

**Comment by naoyuki-sakai** [comment]
WBA 開発会議でタスクの追加依頼あり。
各タスクにカラムを追加し、機能との対応関係を明記する。
こちらは @rondelion さんにて対応するが、別タスクとして管理する。

**Comment by naoyuki-sakai** [comment]
画像の追加を完了。
